server:
  port: 8090

spring:
  application:
    name: "notificationservice"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

config:
  import: "optional:configserver:http://localhost:8888/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    version: "1.0.0"
    name: "Notification Service Development Team"
    message: "Notification service up and ready to schedule appointments"
    contact:
      owner: "Notification Team"
      email: "dev-support@keskink.com"


logging:
  level:
    com:
      keskin:
        notificationservice: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000